/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";

type GLTFResult = GLTF & {
  nodes: {
    odm_textured_model_1: THREE.Mesh;
    odm_textured_model_2: THREE.Mesh;
    odm_textured_model_3: THREE.Mesh;
    odm_textured_model_4: THREE.Mesh;
    odm_textured_model_5: THREE.Mesh;
    odm_textured_model_6: THREE.Mesh;
    odm_textured_model_7: THREE.Mesh;
    odm_textured_model_8: THREE.Mesh;
    odm_textured_model_9: THREE.Mesh;
    odm_textured_model_10: THREE.Mesh;
    odm_textured_model_11: THREE.Mesh;
    odm_textured_model_12: THREE.Mesh;
    odm_textured_model_13: THREE.Mesh;
    odm_textured_model_14: THREE.Mesh;
    odm_textured_model_15: THREE.Mesh;
    odm_textured_model_16: THREE.Mesh;
    odm_textured_model_17: THREE.Mesh;
    odm_textured_model_18: THREE.Mesh;
    odm_textured_model_19: THREE.Mesh;
    odm_textured_model_20: THREE.Mesh;
    odm_textured_model_21: THREE.Mesh;
    odm_textured_model_22: THREE.Mesh;
    odm_textured_model_23: THREE.Mesh;
    odm_textured_model_24: THREE.Mesh;
    odm_textured_model_25: THREE.Mesh;
    odm_textured_model_26: THREE.Mesh;
    odm_textured_model_27: THREE.Mesh;
    odm_textured_model_28: THREE.Mesh;
    odm_textured_model_29: THREE.Mesh;
    odm_textured_model_30: THREE.Mesh;
    odm_textured_model_31: THREE.Mesh;
    odm_textured_model_32: THREE.Mesh;
    odm_textured_model_33: THREE.Mesh;
    odm_textured_model_34: THREE.Mesh;
    odm_textured_model_35: THREE.Mesh;
    odm_textured_model_36: THREE.Mesh;
    odm_textured_model_37: THREE.Mesh;
    odm_textured_model_38: THREE.Mesh;
    odm_textured_model_39: THREE.Mesh;
    odm_textured_model_40: THREE.Mesh;
    odm_textured_model_41: THREE.Mesh;
    odm_textured_model_42: THREE.Mesh;
    odm_textured_model_43: THREE.Mesh;
    odm_textured_model_44: THREE.Mesh;
    odm_textured_model_45: THREE.Mesh;
    odm_textured_model_46: THREE.Mesh;
    odm_textured_model_47: THREE.Mesh;
    odm_textured_model_48: THREE.Mesh;
    odm_textured_model_49: THREE.Mesh;
    odm_textured_model_50: THREE.Mesh;
    odm_textured_model_51: THREE.Mesh;
    odm_textured_model_52: THREE.Mesh;
    odm_textured_model_53: THREE.Mesh;
    odm_textured_model_54: THREE.Mesh;
    odm_textured_model_55: THREE.Mesh;
    odm_textured_model_56: THREE.Mesh;
    odm_textured_model_57: THREE.Mesh;
    odm_textured_model_58: THREE.Mesh;
    odm_textured_model_59: THREE.Mesh;
    odm_textured_model_60: THREE.Mesh;
    odm_textured_model_61: THREE.Mesh;
    odm_textured_model_62: THREE.Mesh;
    odm_textured_model_63: THREE.Mesh;
    odm_textured_model_64: THREE.Mesh;
    odm_textured_model_65: THREE.Mesh;
    odm_textured_model_66: THREE.Mesh;
    odm_textured_model_67: THREE.Mesh;
    odm_textured_model_68: THREE.Mesh;
    odm_textured_model_69: THREE.Mesh;
    odm_textured_model_70: THREE.Mesh;
    odm_textured_model_71: THREE.Mesh;
    odm_textured_model_72: THREE.Mesh;
    odm_textured_model_73: THREE.Mesh;
    odm_textured_model_74: THREE.Mesh;
  };
  materials: {
    material0000: THREE.MeshStandardMaterial;
    material0001: THREE.MeshStandardMaterial;
    material0002: THREE.MeshStandardMaterial;
    material0003: THREE.MeshStandardMaterial;
    material0004: THREE.MeshStandardMaterial;
    material0005: THREE.MeshStandardMaterial;
    material0006: THREE.MeshStandardMaterial;
    material0007: THREE.MeshStandardMaterial;
    material0008: THREE.MeshStandardMaterial;
    material0009: THREE.MeshStandardMaterial;
    material0010: THREE.MeshStandardMaterial;
    material0011: THREE.MeshStandardMaterial;
    material0012: THREE.MeshStandardMaterial;
    material0013: THREE.MeshStandardMaterial;
    material0014: THREE.MeshStandardMaterial;
    material0015: THREE.MeshStandardMaterial;
    material0016: THREE.MeshStandardMaterial;
    material0017: THREE.MeshStandardMaterial;
    material0018: THREE.MeshStandardMaterial;
    material0019: THREE.MeshStandardMaterial;
    material0020: THREE.MeshStandardMaterial;
    material0021: THREE.MeshStandardMaterial;
    material0022: THREE.MeshStandardMaterial;
    material0023: THREE.MeshStandardMaterial;
    material0024: THREE.MeshStandardMaterial;
    material0025: THREE.MeshStandardMaterial;
    material0026: THREE.MeshStandardMaterial;
    material0027: THREE.MeshStandardMaterial;
    material0028: THREE.MeshStandardMaterial;
    material0029: THREE.MeshStandardMaterial;
    material0030: THREE.MeshStandardMaterial;
    material0031: THREE.MeshStandardMaterial;
    material0032: THREE.MeshStandardMaterial;
    material0033: THREE.MeshStandardMaterial;
    material0034: THREE.MeshStandardMaterial;
    material0035: THREE.MeshStandardMaterial;
    material0036: THREE.MeshStandardMaterial;
    material0037: THREE.MeshStandardMaterial;
    material0038: THREE.MeshStandardMaterial;
    material0039: THREE.MeshStandardMaterial;
    material0040: THREE.MeshStandardMaterial;
    material0041: THREE.MeshStandardMaterial;
    material0042: THREE.MeshStandardMaterial;
    material0043: THREE.MeshStandardMaterial;
    material0044: THREE.MeshStandardMaterial;
    material0045: THREE.MeshStandardMaterial;
    material0046: THREE.MeshStandardMaterial;
    material0047: THREE.MeshStandardMaterial;
    material0048: THREE.MeshStandardMaterial;
    material0049: THREE.MeshStandardMaterial;
    material0050: THREE.MeshStandardMaterial;
    material0051: THREE.MeshStandardMaterial;
    material0052: THREE.MeshStandardMaterial;
    material0053: THREE.MeshStandardMaterial;
    material0054: THREE.MeshStandardMaterial;
    material0055: THREE.MeshStandardMaterial;
    material0056: THREE.MeshStandardMaterial;
    material0057: THREE.MeshStandardMaterial;
    material0058: THREE.MeshStandardMaterial;
    material0059: THREE.MeshStandardMaterial;
    material0060: THREE.MeshStandardMaterial;
    material0061: THREE.MeshStandardMaterial;
    material0062: THREE.MeshStandardMaterial;
    material0063: THREE.MeshStandardMaterial;
    material0064: THREE.MeshStandardMaterial;
    material0065: THREE.MeshStandardMaterial;
    material0066: THREE.MeshStandardMaterial;
    material0067: THREE.MeshStandardMaterial;
    material0068: THREE.MeshStandardMaterial;
    material0069: THREE.MeshStandardMaterial;
    material0070: THREE.MeshStandardMaterial;
    material0071: THREE.MeshStandardMaterial;
    material0072: THREE.MeshStandardMaterial;
    material0073: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF("/untitled.glb") as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        position={[-24.9351, 63.8311, -22.2285]}
        rotation={[0.668, 1.2579, -0.5935]}
        userData={{ name: "odm_textured_model" }}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_1.geometry}
          material={materials.material0000}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_2.geometry}
          material={materials.material0001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_3.geometry}
          material={materials.material0002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_4.geometry}
          material={materials.material0003}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_5.geometry}
          material={materials.material0004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_6.geometry}
          material={materials.material0005}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_7.geometry}
          material={materials.material0006}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_8.geometry}
          material={materials.material0007}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_9.geometry}
          material={materials.material0008}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_10.geometry}
          material={materials.material0009}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_11.geometry}
          material={materials.material0010}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_12.geometry}
          material={materials.material0011}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_13.geometry}
          material={materials.material0012}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_14.geometry}
          material={materials.material0013}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_15.geometry}
          material={materials.material0014}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_16.geometry}
          material={materials.material0015}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_17.geometry}
          material={materials.material0016}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_18.geometry}
          material={materials.material0017}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_19.geometry}
          material={materials.material0018}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_20.geometry}
          material={materials.material0019}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_21.geometry}
          material={materials.material0020}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_22.geometry}
          material={materials.material0021}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_23.geometry}
          material={materials.material0022}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_24.geometry}
          material={materials.material0023}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_25.geometry}
          material={materials.material0024}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_26.geometry}
          material={materials.material0025}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_27.geometry}
          material={materials.material0026}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_28.geometry}
          material={materials.material0027}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_29.geometry}
          material={materials.material0028}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_30.geometry}
          material={materials.material0029}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_31.geometry}
          material={materials.material0030}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_32.geometry}
          material={materials.material0031}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_33.geometry}
          material={materials.material0032}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_34.geometry}
          material={materials.material0033}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_35.geometry}
          material={materials.material0034}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_36.geometry}
          material={materials.material0035}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_37.geometry}
          material={materials.material0036}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_38.geometry}
          material={materials.material0037}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_39.geometry}
          material={materials.material0038}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_40.geometry}
          material={materials.material0039}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_41.geometry}
          material={materials.material0040}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_42.geometry}
          material={materials.material0041}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_43.geometry}
          material={materials.material0042}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_44.geometry}
          material={materials.material0043}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_45.geometry}
          material={materials.material0044}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_46.geometry}
          material={materials.material0045}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_47.geometry}
          material={materials.material0046}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_48.geometry}
          material={materials.material0047}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_49.geometry}
          material={materials.material0048}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_50.geometry}
          material={materials.material0049}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_51.geometry}
          material={materials.material0050}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_52.geometry}
          material={materials.material0051}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_53.geometry}
          material={materials.material0052}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_54.geometry}
          material={materials.material0053}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_55.geometry}
          material={materials.material0054}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_56.geometry}
          material={materials.material0055}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_57.geometry}
          material={materials.material0056}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_58.geometry}
          material={materials.material0057}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_59.geometry}
          material={materials.material0058}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_60.geometry}
          material={materials.material0059}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_61.geometry}
          material={materials.material0060}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_62.geometry}
          material={materials.material0061}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_63.geometry}
          material={materials.material0062}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_64.geometry}
          material={materials.material0063}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_65.geometry}
          material={materials.material0064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_66.geometry}
          material={materials.material0065}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_67.geometry}
          material={materials.material0066}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_68.geometry}
          material={materials.material0067}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_69.geometry}
          material={materials.material0068}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_70.geometry}
          material={materials.material0069}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_71.geometry}
          material={materials.material0070}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_72.geometry}
          material={materials.material0071}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_73.geometry}
          material={materials.material0072}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.odm_textured_model_74.geometry}
          material={materials.material0073}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/untitled.glb");
