import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF("/JJDbackgroundremoved.glb")
  console.log(materials)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="odm_textured_model"
          position={[-17.33, 43.93, -14.93]}
          rotation={[0.06, -0.92, 0.13]}
          userData={{ name: "odm_textured_model" }}
        >
          <mesh
            name="odm_textured_model_1"
            castShadow
            receiveShadow
            geometry={nodes.odm_textured_model_1.geometry}
            material={materials.material0000}
          />
          <mesh
            name="odm_textured_model_2"
            castShadow
            receiveShadow
            geometry={nodes.odm_textured_model_2.geometry}
            material={materials.material0001}
          />
          <mesh
            name="odm_textured_model_3"
            castShadow
            receiveShadow
            geometry={nodes.odm_textured_model_3.geometry}
            material={materials.material0002}
          />
          <mesh
            name="odm_textured_model_4"
            castShadow
            receiveShadow
            geometry={nodes.odm_textured_model_4.geometry}
            material={materials.material0003}
          />
          <mesh
            name="odm_textured_model_5"
            castShadow
            receiveShadow
            geometry={nodes.odm_textured_model_5.geometry}
            material={materials.material0004}
          />
          <mesh
            name="odm_textured_model_6"
            castShadow
            receiveShadow
            geometry={nodes.odm_textured_model_6.geometry}
            material={materials.material0005}
          />
          <mesh
            name="odm_textured_model_7"
            castShadow
            receiveShadow
            geometry={nodes.odm_textured_model_7.geometry}
            material={materials.material0006}
          />
          <mesh
            name="odm_textured_model_8"
            castShadow
            receiveShadow
            geometry={nodes.odm_textured_model_8.geometry}
            material={materials.material0007}
          />
          <mesh
            name="odm_textured_model_9"
            castShadow
            receiveShadow
            geometry={nodes.odm_textured_model_9.geometry}
            material={materials.material0008}
          />
          <mesh
            name="odm_textured_model_10"
            castShadow
            receiveShadow
            geometry={nodes.odm_textured_model_10.geometry}
            material={materials.material0009}
          />
          <mesh
            name="odm_textured_model_11"
            castShadow
            receiveShadow
            geometry={nodes.odm_textured_model_11.geometry}
            material={materials.material0010}
          />
          <mesh
            name="odm_textured_model_12"
            castShadow
            receiveShadow
            geometry={nodes.odm_textured_model_12.geometry}
            material={materials.material0011}
          />
          <mesh
            name="odm_textured_model_13"
            castShadow
            receiveShadow
            geometry={nodes.odm_textured_model_13.geometry}
            material={materials.material0012}
          />
          <mesh
            name="odm_textured_model_14"
            castShadow
            receiveShadow
            geometry={nodes.odm_textured_model_14.geometry}
            material={materials.material0013}
          />
          <mesh
            name="odm_textured_model_15"
            castShadow
            receiveShadow
            geometry={nodes.odm_textured_model_15.geometry}
            material={materials.material0014}
          />
          <mesh
            name="odm_textured_model_16"
            castShadow
            receiveShadow
            geometry={nodes.odm_textured_model_16.geometry}
            material={materials.material0015}
          />
          <mesh
            name="odm_textured_model_17"
            castShadow
            receiveShadow
            geometry={nodes.odm_textured_model_17.geometry}
            material={materials.material0016}
          />
          <mesh
            name="odm_textured_model_18"
            castShadow
            receiveShadow
            geometry={nodes.odm_textured_model_18.geometry}
            material={materials.material0017}
          />
          <mesh
            name="odm_textured_model_19"
            castShadow
            receiveShadow
            geometry={nodes.odm_textured_model_19.geometry}
            material={materials.material0018}
          />
          <mesh
            name="odm_textured_model_20"
            castShadow
            receiveShadow
            geometry={nodes.odm_textured_model_20.geometry}
            material={materials.material0019}
          />
          <mesh
            name="odm_textured_model_21"
            castShadow
            receiveShadow
            geometry={nodes.odm_textured_model_21.geometry}
            material={materials.material0020}
          />
          <mesh
            name="odm_textured_model_22"
            castShadow
            receiveShadow
            geometry={nodes.odm_textured_model_22.geometry}
            material={materials.material0021}
          />
          <mesh
            name="odm_textured_model_23"
            castShadow
            receiveShadow
            geometry={nodes.odm_textured_model_23.geometry}
            material={materials.material0022}
          />
          <mesh
            name="odm_textured_model_24"
            castShadow
            receiveShadow
            geometry={nodes.odm_textured_model_24.geometry}
            material={materials.material0023}
          />
          <mesh
            name="odm_textured_model_25"
            castShadow
            receiveShadow
            geometry={nodes.odm_textured_model_25.geometry}
            material={materials.material0024}
          />
          <mesh
            name="odm_textured_model_26"
            castShadow
            receiveShadow
            geometry={nodes.odm_textured_model_26.geometry}
            material={materials.material0025}
          />
          <mesh
            name="odm_textured_model_27"
            castShadow
            receiveShadow
            geometry={nodes.odm_textured_model_27.geometry}
            material={materials.material0026}
          />
          <mesh
            name="odm_textured_model_28"
            castShadow
            receiveShadow
            geometry={nodes.odm_textured_model_28.geometry}
            material={materials.material0027}
          />
          <mesh
            name="odm_textured_model_29"
            castShadow
            receiveShadow
            geometry={nodes.odm_textured_model_29.geometry}
            material={materials.material0028}
          />
          <mesh
            name="odm_textured_model_30"
            castShadow
            receiveShadow
            geometry={nodes.odm_textured_model_30.geometry}
            material={materials.material0029}
          />
          <mesh
            name="odm_textured_model_31"
            castShadow
            receiveShadow
            geometry={nodes.odm_textured_model_31.geometry}
            material={materials.material0030}
          />
          <mesh
            name="odm_textured_model_32"
            castShadow
            receiveShadow
            geometry={nodes.odm_textured_model_32.geometry}
            material={materials.material0031}
          />
          <mesh
            name="odm_textured_model_33"
            castShadow
            receiveShadow
            geometry={nodes.odm_textured_model_33.geometry}
            material={materials.material0032}
          />
          <mesh
            name="odm_textured_model_34"
            castShadow
            receiveShadow
            geometry={nodes.odm_textured_model_34.geometry}
            material={materials.material0033}
          />
          <mesh
            name="odm_textured_model_35"
            castShadow
            receiveShadow
            geometry={nodes.odm_textured_model_35.geometry}
            material={materials.material0034}
          />
          <mesh
            name="odm_textured_model_36"
            castShadow
            receiveShadow
            geometry={nodes.odm_textured_model_36.geometry}
            material={materials.material0035}
          />
          <mesh
            name="odm_textured_model_37"
            castShadow
            receiveShadow
            geometry={nodes.odm_textured_model_37.geometry}
            material={materials.material0036}
          />
          <mesh
            name="odm_textured_model_38"
            castShadow
            receiveShadow
            geometry={nodes.odm_textured_model_38.geometry}
            material={materials.material0037}
          />
          <mesh
            name="odm_textured_model_39"
            castShadow
            receiveShadow
            geometry={nodes.odm_textured_model_39.geometry}
            material={materials.material0038}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload("/JJDbackgroundremoved.glb")
